# This test verifies KVSERROR with keys that never existed and with a key
# that was deleted. It's also a smoke test for the WRITE operation
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
READ [x,z,l,v]
SHOW
DELETE [c]
READ [c]
SHOW
# This test verifies multiple deleted key-values in the same command
# as well as multiple writes in the same command
WRITE [(a,anna)(b,bernardo)]
WRITE [(d,dinis)(c,carlota)]
DELETE [a,b,d]
# this should write only carlota
SHOW
